#!name=Lantern Free Probe v2
#!desc=Shadowrocket motoru başladığında Lantern Free config API'yi doğrudan sorgular ve güvenli transport özetini bildirim olarak gösterir. Tarayıcı/localhost gerekmez.

[Script]
Lantern Free Probe = type=event,event-name=engine-started,timeout=30,engine=jsc,enable=true,script-path=https://raw.githubusercontent.com/omzdmr/lantern-shadowrocket1/main/lantern_shadowrocket_probe_v2.js

[Rule]
DOMAIN,df.iantem.io,DIRECT
