-- Lantern Free TLS 1.2 resumption + SMUX v1 backend for Shadowrocket
-- v16.1 first real connection attempt.
--
-- Node:
--   Type: Lua
--   Address: 89.168.19.95
--   Port: 443
--   TLS: OFF
--   User + Password: compact Base91 material generated by v16 helper.
--
-- Material layout after Base91 decode:
--   121-byte session ticket || 48-byte master secret || 32-byte auth token
--
-- No secret material is embedded in this public file.

local backend = require 'backend'
local crypto = require 'crypto'

local SUCCESS   = backend.RESULT.SUCCESS
local ERROR     = backend.RESULT.ERROR
local HANDSHAKE = backend.RESULT.HANDSHAKE
local IGNORE    = backend.RESULT.IGNORE or backend.RESULT.SUCCESS

local get_uuid = backend.get_uuid
local get_host = backend.get_address_host
local get_port = backend.get_address_port
local write_upstream = backend.write
local free = backend.free
local debug = backend.debug

local SERVER_NAME = 'dotloop.com'
local TLS12 = string.char(0x03, 0x03)
local TICKET_LEN = 121
local MASTER_LEN = 48
local TOKEN_RAW_LEN = 32

local states = {}

local function dbg(st, msg)
    if st then
        if st.last_debug == msg then return end
        st.last_debug = msg
    end
    debug('[lantern-v16.1] ' .. tostring(msg))
end

local function get_username()
    if settings.username and settings.username ~= '' then return settings.username end
    if settings.user and settings.user ~= '' then return settings.user end
    if settings.name and settings.name ~= '' then return settings.name end
    return ''
end

local B91 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,./:;<=>?@[]^_`{|}~"'
local B91MAP = {}
for i = 1, #B91 do
    B91MAP[string.sub(B91, i, i)] = i - 1
end

local function b91decode(s)
    s = tostring(s or ''):gsub('%s', '')
    local out = {}
    local b, n, v = 0, 0, -1
    for i = 1, #s do
        local d = B91MAP[string.sub(s, i, i)]
        if d ~= nil then
            if v < 0 then
                v = d
            else
                v = v + d * 91
                b = b + v * (2 ^ n)
                if (v % 8192) > 88 then n = n + 13 else n = n + 14 end
                while n >= 8 do
                    out[#out + 1] = string.char(b % 256)
                    b = math.floor(b / 256)
                    n = n - 8
                end
                v = -1
            end
        end
    end
    if v >= 0 then
        b = b + v * (2 ^ n)
        out[#out + 1] = string.char(b % 256)
    end
    return table.concat(out)
end

local HEX = '0123456789abcdef'
local function hex_lower(s)
    local out = {}
    for i = 1, #s do
        local b = string.byte(s, i)
        out[#out + 1] = string.sub(HEX, math.floor(b / 16) + 1, math.floor(b / 16) + 1)
        out[#out + 1] = string.sub(HEX, (b % 16) + 1, (b % 16) + 1)
    end
    return table.concat(out)
end

local function load_material()
    local packed = b91decode(get_username() .. tostring(settings.password or ''))
    if #packed ~= (TICKET_LEN + MASTER_LEN + TOKEN_RAW_LEN) then
        return nil, 'material length ' .. tostring(#packed) .. ', expected 201'
    end
    return {
        ticket = string.sub(packed, 1, TICKET_LEN),
        master = string.sub(packed, TICKET_LEN + 1, TICKET_LEN + MASTER_LEN),
        token = hex_lower(string.sub(packed, TICKET_LEN + MASTER_LEN + 1))
    }, nil
end

local function u16be(n)
    return string.char(math.floor(n / 256) % 256, n % 256)
end

local function u24be(n)
    return string.char(math.floor(n / 65536) % 256, math.floor(n / 256) % 256, n % 256)
end

local function u16le(n)
    return string.char(n % 256, math.floor(n / 256) % 256)
end

local function u32le(n)
    local b1 = n % 256
    n = math.floor(n / 256)
    local b2 = n % 256
    n = math.floor(n / 256)
    local b3 = n % 256
    n = math.floor(n / 256)
    local b4 = n % 256
    return string.char(b1, b2, b3, b4)
end

local function read_u16be(s, p)
    local a, b = string.byte(s, p, p + 1)
    return a * 256 + b
end

local function read_u24be(s, p)
    local a, b, c = string.byte(s, p, p + 2)
    return a * 65536 + b * 256 + c
end

local function read_u16le(s, p)
    local a, b = string.byte(s, p, p + 1)
    return a + b * 256
end

local function read_u32le(s, p)
    local a, b, c, d = string.byte(s, p, p + 3)
    return a + b * 256 + c * 65536 + d * 16777216
end

local function u64be_num(n)
    local out = {}
    for i = 8, 1, -1 do
        out[i] = string.char(n % 256)
        n = math.floor(n / 256)
    end
    return table.concat(out)
end

local function xor_byte(a, b)
    local out, p = 0, 1
    for _ = 1, 8 do
        local aa, bb = a % 2, b % 2
        if aa ~= bb then out = out + p end
        a = math.floor(a / 2)
        b = math.floor(b / 2)
        p = p * 2
    end
    return out
end

local function xor_strings(a, b)
    local out = {}
    local n = math.min(#a, #b)
    for i = 1, n do
        out[i] = string.char(xor_byte(string.byte(a, i), string.byte(b, i)))
    end
    return table.concat(out)
end

local function sha256_raw(data)
    local d = crypto.digest.new('sha256')
    d:update(data)
    return d:final(nil, true)
end

local function hmac_sha256(key, data)
    return crypto.hmac.digest('sha256', data, key, true)
end

local function tls_prf(secret, label, seed, out_len)
    local ls = label .. seed
    local a = hmac_sha256(secret, ls)
    local out = {}
    local total = 0
    while total < out_len do
        local block = hmac_sha256(secret, a .. ls)
        out[#out + 1] = block
        total = total + #block
        a = hmac_sha256(secret, a)
    end
    return string.sub(table.concat(out), 1, out_len)
end

local function bytes16(s)
    local t = {}
    for i = 1, 16 do t[i] = string.byte(s, i) or 0 end
    return t
end

local function str16(t)
    return string.char(
        t[1], t[2], t[3], t[4], t[5], t[6], t[7], t[8],
        t[9], t[10], t[11], t[12], t[13], t[14], t[15], t[16]
    )
end

local function xor128(a, b)
    local out = {}
    for i = 1, 16 do out[i] = xor_byte(a[i], b[i]) end
    return out
end

local function rshift1(v)
    local out, carry = {}, 0
    for i = 1, 16 do
        local x = v[i]
        out[i] = math.floor(x / 2) + carry
        carry = (x % 2) * 128
    end
    return out
end

local function gf_mul(x, y)
    local z = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    local v = {}
    for i = 1, 16 do v[i] = y[i] end
    for byte_i = 1, 16 do
        local xb = x[byte_i]
        for bit_i = 7, 0, -1 do
            local bit = math.floor(xb / (2 ^ bit_i)) % 2
            if bit == 1 then z = xor128(z, v) end
            local lsb = v[16] % 2
            v = rshift1(v)
            if lsb == 1 then v[1] = xor_byte(v[1], 0xe1) end
        end
    end
    return z
end

local function aes_ecb_block(key, block)
    local enc = crypto.encrypt.new('aes-128-ecb', key, nil, false)
    return (enc:update(block) or '') .. (enc:final() or '')
end

local function zero_pad_16(s)
    local rem = #s % 16
    if rem == 0 then return s end
    return s .. string.rep('\0', 16 - rem)
end

local function u64be_bits(nbytes)
    local bits = nbytes * 8
    local out = {}
    for i = 8, 1, -1 do
        out[i] = string.char(bits % 256)
        bits = math.floor(bits / 256)
    end
    return table.concat(out)
end

local function ghash(h, aad, ciphertext)
    local y = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
    local hs = bytes16(h)
    local data = zero_pad_16(aad) .. zero_pad_16(ciphertext) ..
                 u64be_bits(#aad) .. u64be_bits(#ciphertext)
    for pos = 1, #data, 16 do
        local block = bytes16(string.sub(data, pos, pos + 15))
        y = gf_mul(xor128(y, block), hs)
    end
    return str16(y)
end

local function inc32(block)
    local b = {string.byte(block, 1, 16)}
    for i = 16, 13, -1 do
        b[i] = b[i] + 1
        if b[i] <= 255 then break end
        b[i] = 0
    end
    return string.char(
        b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8],
        b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16]
    )
end

local function gctr(key, icb, input)
    if #input == 0 then return '' end
    local cb, out, pos = icb, {}, 1
    while pos <= #input do
        local block = string.sub(input, pos, pos + 15)
        local stream = aes_ecb_block(key, cb)
        out[#out + 1] = xor_strings(block, string.sub(stream, 1, #block))
        cb = inc32(cb)
        pos = pos + 16
    end
    return table.concat(out)
end

local function gcm_seal_96(key, iv12, aad, plaintext)
    local h = aes_ecb_block(key, string.rep('\0', 16))
    local j0 = iv12 .. string.char(0,0,0,1)
    local c = gctr(key, inc32(j0), plaintext)
    local tag = xor_strings(aes_ecb_block(key, j0), ghash(h, aad, c))
    return c, tag
end

local function gcm_open_96(key, iv12, aad, ciphertext, tag)
    local h = aes_ecb_block(key, string.rep('\0', 16))
    local j0 = iv12 .. string.char(0,0,0,1)
    local expected = xor_strings(aes_ecb_block(key, j0), ghash(h, aad, ciphertext))
    if expected ~= tag then return nil, 'gcm tag mismatch' end
    return gctr(key, inc32(j0), ciphertext), nil
end

local function tls_record(typ, ver, payload)
    return string.char(typ) .. ver .. u16be(#payload) .. payload
end

local function hs_msg(typ, body)
    return string.char(typ) .. u24be(#body) .. body
end

local function ext(typ, body)
    return u16be(typ) .. u16be(#body) .. body
end

local function build_client_hello(st)
    st.client_random = crypto.rand.bytes(32)
    st.client_sid = crypto.rand.bytes(32)

    local suites = {
        0xc02b,
        0xc02f, 0xc02c, 0xc030,
        0xcca9, 0xcca8,
        0xc009, 0xc00a, 0xc013, 0xc014,
        0x009c, 0x009d, 0x002f, 0x0035
    }
    local suite_bytes = {}
    for _, s in ipairs(suites) do suite_bytes[#suite_bytes + 1] = u16be(s) end
    suite_bytes = table.concat(suite_bytes)

    local sni_name = SERVER_NAME
    local sni_entry = string.char(0) .. u16be(#sni_name) .. sni_name
    local sni = u16be(#sni_entry) .. sni_entry

    local groups = u16be(6) .. u16be(0x001d) .. u16be(0x0017) .. u16be(0x0018)
    local points = string.char(1, 0)

    local sigs_list =
        u16be(0x0403) .. u16be(0x0503) .. u16be(0x0603) ..
        u16be(0x0804) .. u16be(0x0805) .. u16be(0x0806) ..
        u16be(0x0401) .. u16be(0x0501) .. u16be(0x0601)
    local sigs = u16be(#sigs_list) .. sigs_list

    local status_request = string.char(1) .. u16be(0) .. u16be(0)
    local reneg = string.char(0)

    local extensions =
        ext(0x0000, sni) ..
        ext(0x0005, status_request) ..
        ext(0x000a, groups) ..
        ext(0x000b, points) ..
        ext(0x000d, sigs) ..
        ext(0x0017, '') ..
        ext(0x0023, st.ticket) ..
        ext(0xff01, reneg)

    local body =
        TLS12 ..
        st.client_random ..
        string.char(#st.client_sid) .. st.client_sid ..
        u16be(#suite_bytes) .. suite_bytes ..
        string.char(1, 0) ..
        u16be(#extensions) .. extensions

    local msg = hs_msg(1, body)
    st.transcript = msg
    return tls_record(22, string.char(0x03, 0x01), msg)
end

local function derive_keys(st)
    local key_block = tls_prf(st.master, 'key expansion', st.server_random .. st.client_random, 40)
    st.client_key = string.sub(key_block, 1, 16)
    st.server_key = string.sub(key_block, 17, 32)
    st.client_iv = string.sub(key_block, 33, 36)
    st.server_iv = string.sub(key_block, 37, 40)
end

local function parse_server_hello(st, raw)
    if #raw < 42 then return nil, 'short ServerHello' end
    local body = string.sub(raw, 5)
    local ver = string.sub(body, 1, 2)
    if ver ~= TLS12 then return nil, 'server chose non-TLS1.2' end

    st.server_random = string.sub(body, 3, 34)
    local sid_len = string.byte(body, 35)
    local p = 36
    if #body < p + sid_len + 2 then return nil, 'bad ServerHello sid' end
    local sid = string.sub(body, p, p + sid_len - 1)
    p = p + sid_len
    local suite = read_u16be(body, p)
    p = p + 2
    local compression = string.byte(body, p)
    if suite ~= 0xc02b then return nil, string.format('cipher 0x%04x', suite) end
    if compression ~= 0 then return nil, 'compression not null' end

    st.resume_sid_match = (sid == st.client_sid)
    st.transcript = st.transcript .. raw
    derive_keys(st)
    st.got_server_hello = true
    dbg(st, 'ServerHello TLS1.2 c02b, sid_match=' .. tostring(st.resume_sid_match))
    return true, nil
end

local function tls_encrypt_record(st, typ, plaintext)
    local seq = st.write_seq
    local explicit = u64be_num(seq)
    local aad = u64be_num(seq) .. string.char(typ) .. TLS12 .. u16be(#plaintext)
    local c, tag = gcm_seal_96(st.client_key, st.client_iv .. explicit, aad, plaintext)
    st.write_seq = seq + 1
    return tls_record(typ, TLS12, explicit .. c .. tag)
end

local function tls_decrypt_record(st, typ, payload)
    if #payload < 24 then return nil, 'short AEAD record' end
    local explicit = string.sub(payload, 1, 8)
    local ciphertext = string.sub(payload, 9, #payload - 16)
    local tag = string.sub(payload, #payload - 15)
    local seq = st.read_seq
    local aad = u64be_num(seq) .. string.char(typ) .. TLS12 .. u16be(#ciphertext)
    local plain, err = gcm_open_96(st.server_key, st.server_iv .. explicit, aad, ciphertext, tag)
    if not plain then return nil, err end
    st.read_seq = seq + 1
    return plain, nil
end

local function build_client_finished(st)
    local verify = tls_prf(st.master, 'client finished', sha256_raw(st.transcript), 12)
    local raw = hs_msg(20, verify)
    st.transcript = st.transcript .. raw
    return raw
end

local function verify_server_finished(st, raw)
    local body = string.sub(raw, 5)
    if #body ~= 12 then return nil, 'server Finished len=' .. tostring(#body) end
    local expected = tls_prf(st.master, 'server finished', sha256_raw(st.transcript), 12)
    if body ~= expected then return nil, 'server Finished verify mismatch' end
    st.transcript = st.transcript .. raw
    return true, nil
end

local VERSION = 1
local CMD_SYN = 0
local CMD_FIN = 1
local CMD_PSH = 2
local CMD_NOP = 3
local STREAM_ID = 1
local MAX_SMUX_PAYLOAD = 16000

local function smux_frame(cmd, sid, payload)
    payload = payload or ''
    return string.char(VERSION, cmd) .. u16le(#payload) .. u32le(sid) .. payload
end

local function smux_data(payload)
    local out, pos = {}, 1
    while pos <= #payload do
        local last = math.min(pos + MAX_SMUX_PAYLOAD - 1, #payload)
        out[#out + 1] = smux_frame(CMD_PSH, STREAM_ID, string.sub(payload, pos, last))
        pos = last + 1
    end
    return table.concat(out)
end

local function target_for(ctx)
    local host = get_host(ctx)
    local port = get_port(ctx)
    if string.find(host, ':', 1, true) and string.sub(host, 1, 1) ~= '[' then
        host = '[' .. host .. ']'
    end
    return host .. ':' .. tostring(port)
end

local function connect_request(st, ctx)
    local target = target_for(ctx)
    return
        'CONNECT ' .. target .. ' HTTP/1.1\r\n' ..
        'Host: ' .. target .. '\r\n' ..
        'Proxy-Connection: Keep-Alive\r\n' ..
        'User-Agent: Go-http-client/1.1\r\n' ..
        'X-Lantern-Auth-Token: ' .. st.token .. '\r\n' ..
        'X-Lantern-Device-Id: a34113\r\n' ..
        'X-Lantern-Version: 7.6.179\r\n' ..
        'X-Lantern-App-Version: 9999.99.99\r\n' ..
        'X-Lantern-Platform: android\r\n' ..
        'X-Lantern-Pro-Token: K1qttSsZruN\r\n' ..
        'X-Lantern-User-Id: 381696446\r\n' ..
        'X-Lantern-Time-Zone: Asia/Shanghai\r\n' ..
        'X-BBR: y\r\n' ..
        '\r\n'
end

local function tls_wrap_application(st, plaintext)
    local out, pos = {}, 1
    while pos <= #plaintext do
        local last = math.min(pos + 16383, #plaintext)
        out[#out + 1] = tls_encrypt_record(st, 23, string.sub(plaintext, pos, last))
        pos = last + 1
    end
    return table.concat(out)
end

local function start_smux(st, ctx)
    local initial = smux_frame(CMD_SYN, STREAM_ID, '') .. smux_data(connect_request(st, ctx))
    write_upstream(ctx, tls_wrap_application(st, initial))
    st.smux_started = true
    dbg(st, 'TLS resumed; SMUX CONNECT sent')
end

local function parse_smux(st, incoming)
    st.smux_raw = st.smux_raw .. (incoming or '')
    local payloads = {}
    local saw_fin = false

    while #st.smux_raw >= 8 do
        local ver = string.byte(st.smux_raw, 1)
        local cmd = string.byte(st.smux_raw, 2)
        local len = read_u16le(st.smux_raw, 3)
        local sid = read_u32le(st.smux_raw, 5)
        local total = 8 + len
        if #st.smux_raw < total then break end

        local payload = ''
        if len > 0 then payload = string.sub(st.smux_raw, 9, total) end
        st.smux_raw = string.sub(st.smux_raw, total + 1)

        if ver ~= VERSION then return nil, 'smux version ' .. tostring(ver), false end
        if cmd == CMD_NOP then
        elseif sid == STREAM_ID then
            if cmd == CMD_PSH and #payload > 0 then
                payloads[#payloads + 1] = payload
            elseif cmd == CMD_FIN then
                saw_fin = true
            end
        end
    end

    return table.concat(payloads), nil, saw_fin
end

local function process_tunneled_plain(st, plain)
    local stream_bytes, err, saw_fin = parse_smux(st, plain)
    if err then return nil, err, false end

    if not st.connect_ok then
        if #stream_bytes > 0 then st.connect_buf = st.connect_buf .. stream_bytes end
        local p = string.find(st.connect_buf, '\r\n\r\n', 1, true)
        if not p then
            if saw_fin then return nil, 'smux FIN before CONNECT response', false end
            return '', nil, false
        end
        local header = string.sub(st.connect_buf, 1, p + 3)
        local code = tonumber(string.match(header, '^HTTP/%d+%.%d+%s+(%d+)') or '0')
        if code < 200 or code >= 300 then
            return nil, 'CONNECT status ' .. tostring(code), false
        end
        st.connect_ok = true
        dbg(st, 'CONNECT established status=' .. tostring(code))
        local tail = string.sub(st.connect_buf, p + 4)
        st.connect_buf = ''
        return tail, nil, true
    end

    if saw_fin and #stream_bytes == 0 then return nil, 'smux FIN', false end
    return stream_bytes, nil, false
end

local function new_state(ctx)
    local material, err = load_material()
    if not material then return nil, err end
    return {
        ticket = material.ticket,
        master = material.master,
        token = material.token,
        started = false,
        got_server_hello = false,
        read_cipher = false,
        tls_ready = false,
        smux_started = false,
        connect_ok = false,
        handshake_notified = false,
        tls_raw = '',
        hs_raw = '',
        transcript = '',
        read_seq = 0,
        write_seq = 0,
        smux_raw = '',
        connect_buf = ''
    }, nil
end

local function get_state(ctx)
    local id = get_uuid(ctx)
    local st = states[id]
    if st then return st, nil end
    local err
    st, err = new_state(ctx)
    if not st then return nil, err end
    states[id] = st
    return st, nil
end

local function process_plain_handshake(st, data)
    st.hs_raw = st.hs_raw .. data
    while #st.hs_raw >= 4 do
        local typ = string.byte(st.hs_raw, 1)
        local len = read_u24be(st.hs_raw, 2)
        local total = 4 + len
        if #st.hs_raw < total then break end
        local raw = string.sub(st.hs_raw, 1, total)
        st.hs_raw = string.sub(st.hs_raw, total + 1)

        if not st.got_server_hello then
            if typ ~= 2 then return nil, 'expected ServerHello, got hs=' .. tostring(typ) end
            local ok, err = parse_server_hello(st, raw)
            if not ok then return nil, err end
        else
            return nil, 'ticket rejected; full handshake hs=' .. tostring(typ)
        end
    end
    return true, nil
end

local function process_encrypted_handshake(st, data)
    st.hs_raw = st.hs_raw .. data
    while #st.hs_raw >= 4 do
        local typ = string.byte(st.hs_raw, 1)
        local len = read_u24be(st.hs_raw, 2)
        local total = 4 + len
        if #st.hs_raw < total then break end
        local raw = string.sub(st.hs_raw, 1, total)
        st.hs_raw = string.sub(st.hs_raw, total + 1)

        if typ == 20 then
            local ok, err = verify_server_finished(st, raw)
            if not ok then return nil, err end

            local client_finished = build_client_finished(st)
            st.write_seq = 0
            local ccs = tls_record(20, TLS12, string.char(1))
            local fin = tls_encrypt_record(st, 22, client_finished)
            write_upstream(st.ctx, ccs .. fin)
            st.tls_ready = true
            dbg(st, 'server Finished verified; client Finished sent')
            start_smux(st, st.ctx)
        else
            st.transcript = st.transcript .. raw
            dbg(st, 'encrypted handshake message=' .. tostring(typ))
        end
    end
    return true, nil
end

local function process_tls_input(st, buf)
    st.tls_raw = st.tls_raw .. (buf or '')
    local output = {}
    local became_connected = false

    while #st.tls_raw >= 5 do
        local typ = string.byte(st.tls_raw, 1)
        local len = read_u16be(st.tls_raw, 4)
        if #st.tls_raw < 5 + len then break end
        local payload = string.sub(st.tls_raw, 6, 5 + len)
        st.tls_raw = string.sub(st.tls_raw, 6 + len)

        if typ == 21 and not st.read_cipher then
            local level, desc = string.byte(payload, 1, 2)
            return nil, 'TLS alert ' .. tostring(level) .. '/' .. tostring(desc), false
        end

        if not st.read_cipher then
            if typ == 22 then
                local ok, err = process_plain_handshake(st, payload)
                if not ok then return nil, err, false end
            elseif typ == 20 then
                if not st.got_server_hello then return nil, 'CCS before ServerHello', false end
                st.read_cipher = true
                st.read_seq = 0
                st.hs_raw = ''
                dbg(st, 'server CCS; resumption path entered')
            end
        else
            local plain, err = tls_decrypt_record(st, typ, payload)
            if not plain then return nil, err, false end

            if typ == 22 then
                local ok
                ok, err = process_encrypted_handshake(st, plain)
                if not ok then return nil, err, false end
            elseif typ == 23 then
                if not st.tls_ready then return nil, 'application data before Finished', false end
                local tunneled, e, connected_now = process_tunneled_plain(st, plain)
                if e then return nil, e, false end
                if tunneled and #tunneled > 0 then output[#output + 1] = tunneled end
                if connected_now then became_connected = true end
            elseif typ == 21 then
                return nil, 'encrypted TLS alert', false
            end
        end
    end

    return table.concat(output), nil, became_connected
end

function wa_lua_on_flags_cb(ctx)
    local st, err = get_state(ctx)
    if not st then debug('[lantern-v16.1] material error: ' .. tostring(err)) end
    return 0
end

function wa_lua_on_handshake_cb(ctx)
    local st, err = get_state(ctx)
    if not st then
        debug('[lantern-v16.1] material error: ' .. tostring(err))
        return false
    end
    st.ctx = ctx

    if st.connect_ok then return true end

    if not st.started then
        local hello = build_client_hello(st)
        write_upstream(ctx, hello)
        st.started = true
        dbg(st, 'ClientHello sent, ticket_len=' .. tostring(#st.ticket))
    end
    return false
end

function wa_lua_on_read_cb(ctx, buf)
    local st, err = get_state(ctx)
    if not st then
        debug('[lantern-v16.1] material error: ' .. tostring(err))
        return ERROR, nil
    end
    st.ctx = ctx

    local plain, perr, connected_now = process_tls_input(st, buf)
    if perr then
        dbg(st, 'ERROR ' .. tostring(perr))
        return ERROR, nil
    end

    if connected_now and not st.handshake_notified then
        st.handshake_notified = true
        if plain and #plain > 0 then return HANDSHAKE, plain end
        return HANDSHAKE, nil
    end

    if st.connect_ok then
        if plain and #plain > 0 then return SUCCESS, plain end
        return IGNORE, nil
    end

    return IGNORE, nil
end

function wa_lua_on_write_cb(ctx, buf)
    local st, err = get_state(ctx)
    if not st or not st.connect_ok then return IGNORE, nil end
    local framed = smux_data(buf or '')
    return SUCCESS, tls_wrap_application(st, framed)
end

function wa_lua_on_close_cb(ctx)
    local id = get_uuid(ctx)
    local st = states[id]
    if st and st.tls_ready and st.smux_started then
        pcall(function()
            local fin = smux_frame(CMD_FIN, STREAM_ID, '')
            write_upstream(ctx, tls_wrap_application(st, fin))
        end)
    end
    states[id] = nil
    free(ctx)
    return SUCCESS
end
