#!name=Lantern Free Probe v5
#!desc=Çin'den erişilebilir Xiaomi HTTP adresi üzerinden önce Shadowrocket script motorunu doğrular, sonra Lantern Free config API'yi sorgular.

[Script]
Lantern Free Probe v5 = type=http-request,pattern=^http:\/\/connect\.rom\.miui\.com\/lantern-(?:check|run)(?:\?.*)?$,requires-body=false,timeout=30,engine=webview,script-path=https://raw.githubusercontent.com/omzdmr/lantern-shadowrocket1/main/lantern_shadowrocket_probe_v5.js,enable=true

[Rule]
DOMAIN,connect.rom.miui.com,DIRECT
DOMAIN,df.iantem.io,DIRECT
