#!name=Lantern Free Probe v6
#!desc=HTTPS+MITM ile Shadowrocket script motorunu doğrular ve ardından Lantern Free config API'yi sorgular.

[Script]
Lantern Free Probe v6 = type=http-request,pattern=^https:\/\/connect\.rom\.miui\.com\/lantern-(?:check|run)(?:\?.*)?$,requires-body=false,timeout=30,engine=webview,script-path=https://raw.githubusercontent.com/omzdmr/lantern-shadowrocket1/main/lantern_shadowrocket_probe_v6.js,enable=true

[Rule]
DOMAIN,connect.rom.miui.com,DIRECT
DOMAIN,df.iantem.io,DIRECT

[MITM]
hostname = %APPEND% connect.rom.miui.com
enable = true
